#!/bin/sh

location=${1:-/}

df -h / | awk ' /[0-9]/ {
gsub(/[^0-9]/, "", $5)
perc = sprintf("%d", $5)
print $3 "/" $2 " " perc "%"
print $3 "/" $2 " " perc "%"
if (perc > 90) {
    print "#FF0000"
}
else if(perc > 80) {
    print "#FFFC00"
}
}'
