#!/bin/sh

WARN=80
CRIT=90

awk -v warn=$WARN -v crit=$CRIT '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
END {
	perc = (1 - (mem_free / mem_total)) * 100
	printf(" %.1f%\n", perc)
	printf(" %.1f%\n", perc)
	if (perc > crit) {
		printf("#FF0000\n")
	} else if (perc > warn) {
		printf("#FFFC00\n")
	}
}
' /proc/meminfo
