#!/usr/bin/env bash

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -n 1)
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk -F': ' '{print $2}')

if [[ "$mute" == "yes" ]]; then
    printf " \n"
    printf " \n"
    printf "#FFFC00"
else
    printf "  %d%%\n" $volume
fi
