#!/bin/sh

case "$(file --dereference --brief --mime-type -- "$1")" in
    text/* | */xml | application/json) bat --terminal-width "$(($4-2))" -f "$1" ;;
    video/*) mediainfo "$1";;
    image/*) exif "$1";;
esac
exit 0
