# man 5 alacritty

[window]
decorations = "full"
decorations_theme_variant = "dark"
dynamic_title = true
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"
class = { general = "Alacritty", instance = "Alacritty" }
dimensions = { columns = 140, lines = 50 }
padding = { x = 0, y = 0}

[cursor]
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true
style = { blinking = "On", shape="Block" }

[font]
size = 8.0
normal        = { family="UbuntuMono Nerd Font", style="Regular" }
bold          = { family="UbuntuMono Nerd Font", style="Bold" }
bold_italic   = { family="UbuntuMono Nerd Font", style="Bold Italic" }
italic        = { family="UbuntuMono Nerd Font", style="Italic" }

[keyboard]
bindings = [
{ key = "Paste", action = "Paste" },
{ key = "Copy", action = "Copy" },
{ key = "Copy", action = "Copy" },
{ key = "L", mods = "Control", action = "ClearLogNotice" },
{ key = "L", mods = "Control", chars = "\f", mode = "~Vi|~Search"},
{ action = "ScrollPageUp",key = "PageUp",mode = "~Alt",mods = "None" },
{ action = "ScrollPageDown", key = "PageDown", mode = "~Alt", mods = "None" },
{ action = "ScrollToTop", key = "Home", mode = "~Alt", mods = "Shift" },
{ action = "ScrollToBottom", key = "End", mode = "~Alt", mods = "Shift" },
{ action = "ToggleFullscreen", key = "F11" },
{ action = "PasteSelection", key = "Insert", mods = "Shift" },
{ action = "Paste", key = "V", mods = "Control|Shift" },
{ action = "Copy", key = "C", mods = "Control|Shift" },
{ action = "ResetFontSize", key = "Key0", mods = "Control" },
{ action = "IncreaseFontSize", key = "Plus", mods = "Control" },
{ action = "DecreaseFontSize", key = "Minus", mods = "Control" },
{ action = "SpawnNewInstance", key = "T", mods = "Control|Shift" },
{ action = "SpawnNewInstance", key = "N", mods = "Control|Shift" },
]

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login", "-c", "tmux new-session -As default"]
program = "/usr/bin/zsh"


[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "0x10100E"
foreground = "0xC6C6C4"
